[package]
name = "openexr"
version = "3.0.1"
authors = ["Anders Langlands <anderslanglands@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openexr-sys = {path="../build/openexr-sys"}
half = "1.7.1"
thiserror = "1.0.24"
bitflags = "1.2.1"

[dev-dependencies]
png = "0.16.8"
itertools = "0.10.0"
